[package]
name = "commitblue/blueserializer"
description = "A serializer to serialize roblox's primitive types into tables. and a deserializer"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["module"]
exclude = ["default.project.json"]
[dependencies]